#include "./estruturas/cidade.cpp"
#include "./estruturas/curso.cpp"
#include "./estruturas/instrutor.cpp"
#include "./estruturas/aluno.cpp"
#include "./estruturas/turma.cpp"
#include "./estruturas/matricula.cpp"